-- Ad-level insights (4th drill-down level). Synced via POST /api/meta/sync with level=ad.
CREATE TABLE meta_ad_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES meta_ad_accounts(account_id),
  campaign_id text,
  campaign_name text NOT NULL,
  adset_id text,
  adset_name text NOT NULL,
  ad_id text NOT NULL,
  ad_name text NOT NULL,
  date date NOT NULL,
  spend numeric DEFAULT 0,
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  results integer DEFAULT 0,
  cost_per_result numeric DEFAULT 0,
  cpm numeric DEFAULT 0,
  cpc numeric DEFAULT 0,
  ctr numeric DEFAULT 0,
  reach integer DEFAULT 0,
  frequency numeric DEFAULT 0,
  video_p25_watched integer DEFAULT 0,
  video_p50_watched integer DEFAULT 0,
  video_p75_watched integer DEFAULT 0,
  video_p100_watched integer DEFAULT 0,
  video_thruplay integer DEFAULT 0,
  account_currency text DEFAULT 'USD',
  fetched_at timestamptz DEFAULT now(),
  UNIQUE(account_id, ad_id, date)
);
